### ISSUE TITLE
awf-extended is showing wrong text for tabs, tab3! and not tab3  

### ISSUE THREAD

**Issue by ChooChooAl** [luigifab/awf-extended#8]
awf-gtk3 2.5.0 is showing the wrong labels for tabs in the bottom of the screen.
All but Tab3 are right.  Tab3 is labeled tab3!   I think it's a typo?
![awf](https://user-images.githubusercontent.com/26556059/231564696-5ff99787-16b6-4303-a180-408a40a381ee.png)
@luigifab

**Comment by luigifab** [comment]
No this is not a typo.
But you are right: it's useless for horizontal tabs.
It's helpful for vertical tabs to have different label width.

I changed the labels for the next release (v2.7):

![image](https://user-images.githubusercontent.com/31816829/231576855-2f4152d3-e092-4b49-ad8e-88836d400166.png)

**Comment by ChooChooAl** [comment]
I don't see my problem on your picture but on mine the tab3 has an explamation point after it.  Thats the typo I'm referring to.

**Comment by luigifab** [comment]
Changed in v2.7.0.
